api_platform:
    title: RSVP Reading API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        http_auth:
            JWT:
                scheme: bearer
                bearerFormat: JWT
